from pathlib import Path
p=Path('lmstudio-context-compactor-plugin/src/prediction-loop.ts')
s=p.read_text(encoding='utf-8')
s='import { ExecutionState, RoundTransaction } from "./execution-state";\n'+s
s=s.replace('  let finalizationPending = false;\n  let finalizationTrigger: FinalizationTrigger | null = null;', '  const execution = new ExecutionState();')
s=s.replace('  let toolPlanningRetryPending = false;\n','').replace('  let researchRecoveryProfileActive = false;\n','')
import re
s=re.sub(r'( *)researchRecoveryProfileActive = false;\n(?=\s*finalizationPending = true;)', '', s)
s=re.sub(r'finalizationPending = true;\n\s*finalizationTrigger = ([^;]+);',r'execution.finishResearch(\1);',s)
s=s.replace('        finalizationPending = false;\n        finalizationTrigger = null;\n','')
s=s.replace('        toolPlanningRetryPending = true;', '        execution.startReplan();')
s=s.replace('        researchRecoveryProfileActive = true;\n        researchRecoveryToolNames', '        researchRecoveryToolNames')
s=s.replace('researchRecoveryProfileActive = true;', 'execution.startRecovery("context_budget");')
s=s.replace('researchRecoveryProfileActive = false;', 'execution.endRecovery();')
s=s.replace('if (toolPlanningRetryRound) toolPlanningRetryPending = false;', 'if (toolPlanningRetryRound) execution.finishReplan();')
s=s.replace('finalizationPending,', 'finalizationPending: execution.finalizing,')
s=s.replace('finalizationTrigger,', 'finalizationTrigger: execution.finalizationTrigger,')
s=re.sub(r'(?<![\w.:])finalizationPending(?!:)', 'execution.finalizing', s)
s=re.sub(r'(?<![\w.:])finalizationTrigger(?!:)', 'execution.finalizationTrigger', s)
s=s.replace('researchRecoveryProfileActive', 'execution.recovering').replace('toolPlanningRetryPending','execution.replanning')
s=s.replace('      let noteLifecycle = activeNote', '      const transaction = new RoundTransaction(captured, roundSignal.aborted);\n      let noteLifecycle = activeNote')
s=s.replace('if (noteEnabled && extracted.note)', 'if (transaction.planningCommitted && noteEnabled && extracted.note)')
s=s.replace('        workingHistory.append(historyMessage);', '        const durableMessage = transaction.durable(historyMessage);\n        if (durableMessage) workingHistory.append(durableMessage);')
s=s.replace('  } finally {\n    activeActivity', '  } finally {\n    execution.terminate(ctl.abortSignal.aborted ? "canceled" : "execution_finished");\n    if (config.showDebugInfo) ctl.debug({ event: "execution_transitions", phase: execution.phase, transitions: execution.transitions });\n    activeActivity')
p.write_text(s,encoding='utf-8')
